.TH SC88SYSEX 1 "20 Feb 2005"

.SH NAME
sc88sysex \- Roland SC-88 System Exclusive Librarian

.SH SYNOPSIS
.B sc88sysex
[-v] [-h] [-p PORT] [-d DEVICEID] [-t TIMEOUT] {-a ADDRESS -z SIZE | -c
COMMAND} [-r|-s FILENAME]

.SH DESCRIPTION
.B sc88sysex
is a command-line utility that helps to send and receive system exclusive data
to/from a Roland SC-88 device using ALSA raw MIDIports. This program is a Bash
script using
.B amidi(1).

.SH OPTIONS
.TP
.I -h
Prints a help message.

.TP
.I -v
Prints more verbose messages.

.TP
.I -p PORT
Sets the raw MIDI port to which receive and send SYSEX messages.

.TP
.I -d DEVICEID
Sets the device number assigned to the SC-88 in the MIDI network.

.TP
.I -t TIMEOUT
Sets the number of seconds to wait for data before closing the
receiving session.

.TP
.I -a ADDRESS
Sets the address of the system exclusive data to be transferred.
It can be a symbolic name or three hex constants. See the output of 
.I -h
to get a list of the predefined symbolic addresses.

.TP
.I -z SIZE
Sets the size of the system exclusive transfer. It can be a symbolic
name or three hex constants. See the output of 
.I -h
to get a list of the predefined symbolic sizes.

.TP
.I -c COMMAND
Sets a command to be sent to the SC-88 as a system exclusive message.
It can be a symbolic name or three hex constants. See the output of 
.I -h
to get a list of the predefined commands.

.TP
.I -r FILE
Save the receive data under this file name (optional).
If not specified, the file name is built upon the given address 
and size arguments.

.TP
.I -s FILE
Sends the contents of this file name.

.SH FILES
.I ~/.sc88sysexrc
personal configuration
.br
.I /etc/sc88sysexrc
system wide configuration
.br

You can set your preferred default options in a config file either in your
home directory or as a global configuration file in /etc. The format is simply
a set of lines having a expression of VARIABLE=value type. You can add more
symbolic addresses, sizes and commands here.

If you don't provide one, the following default options take effect:

.br
.I MIDIPORT="hw:0"
.br
.I DEVICEID=10
.br
.I TIMEOUT=3
.br
.I LIBDIR=~/SC88LIB

.SH EXAMPLES
.TP
.B sc88sysex -a BULKDUMP -z ALL
Sends a bulk dump request using the default MIDI port to the SC-88, and stores
the received data in a file named "sc88_bulkdump_all.syx"

.TP
.B sc88sysex -c GSRESET
Sends a GS reset command to the SC-88

.TP
.B sc88sysex -s dump.syx
Sends a data file "dump.syx" to the SC-88.

.TP
.B sc88sysex -a '40 00 00' -z '00 00 04' -r deftune.syx
Gets the master tune parameter from the SC-88 saving it on a file named 
"deftune.syx"

.SH SEE ALSO
amidi(1)

.SH AUTHOR
Pedro Lopez-Cabanillas <plcl@users.sourceforge.net>
